import { Spin } from 'antd';
import {
    CaretLeftOutlined,CheckCircleFilled,
    CaretUpOutlined ,VerticalAlignBottomOutlined,
    UpOutlined, FileSearchOutlined,RiseOutlined,
    DownOutlined,BackwardOutlined,SettingOutlined,
    ArrowsAltOutlined,ShrinkOutlined,QuestionCircleOutlined,
    StepBackwardOutlined,CloseCircleOutlined,
    FastForwardOutlined,CheckCircleOutlined,
    FastBackwardOutlined,HddFilled, CheckSquareOutlined,
    StepForwardOutlined,SyncOutlined,SmallDashOutlined,
    MoneyCollectFilled,LoadingOutlined, ExclamationCircleOutlined,
    RightOutlined,EyeFilled,FileExclamationFilled,RetweetOutlined,
    InfoCircleFilled,ExclamationCircleFilled,CalendarFilled,
    CaretDownOutlined,VerticalAlignTopOutlined,RollbackOutlined,
    CaretRightOutlined,VerticalRightOutlined,ForwardOutlined,SlidersFilled,
    UpCircleOutlined,DoubleRightOutlined,DoubleLeftOutlined,VerticalLeftOutlined,
    DownCircleOutlined, LeftCircleOutlined,RightCircleOutlined,BulbFilled, ShopFilled,
    AccountBookOutlined,PieChartFilled,IdcardFilled,PlayCircleOutlined
} from "@ant-design/icons";

const icon = {
    Spin: <Spin />,
    SyncOutlined:<SyncOutlined spin />,
    LoadingOutlined:<LoadingOutlined />,
    CaretRightOutlined: <CaretRightOutlined />,
        CaretLeftOutlined: <CaretLeftOutlined />,
        CaretDownOutlined: <CaretDownOutlined />,
        CaretUpOutlined: <CaretUpOutlined />,
        FastBackwardOutlined: <FastBackwardOutlined />,
        UpOutlined: <UpOutlined />,
        DownOutlined: <DownOutlined />,
        ArrowsAltOutlined: <ArrowsAltOutlined />,
        ShrinkOutlined: <ShrinkOutlined />,
        FastForwardOutlined: <FastForwardOutlined />,
        StepBackwardOutlined: <StepBackwardOutlined />,
        MoneyCollectFilled: <MoneyCollectFilled />,
        StepForwardOutlined: <StepForwardOutlined />,
        RightOutlined: <RightOutlined />,
        UpCircleOutlined: <UpCircleOutlined />,
        DownCircleOutlined: <DownCircleOutlined />,
        LeftCircleOutlined: <LeftCircleOutlined />,
        RightCircleOutlined: <RightCircleOutlined />,

        DoubleRightOutlined: <DoubleRightOutlined />,
        DoubleLeftOutlined: <DoubleLeftOutlined />,

        VerticalLeftOutlined: <VerticalLeftOutlined />,
        VerticalRightOutlined:<VerticalRightOutlined />,
        VerticalAlignTopOutlined:<VerticalAlignTopOutlined />,
        VerticalAlignBottomOutlined:<VerticalAlignBottomOutlined />,

        ForwardOutlined:<ForwardOutlined />,
        BackwardOutlined:<BackwardOutlined />,

        RollbackOutlined:<RollbackOutlined />,
        InfoCircleFilled:<InfoCircleFilled />,
        ExclamationCircleFilled:<ExclamationCircleFilled  />,
        EyeFilled:<EyeFilled />,
        BulbFilled:<BulbFilled />,
        CheckCircleFilled:<CheckCircleFilled />,
        FileExclamationFilled:<FileExclamationFilled />,
        ShopFilled:<ShopFilled />,
        SlidersFilled:<SlidersFilled />,
        CalendarFilled:<CalendarFilled />,
        HddFilled:<HddFilled />,
        AccountBookOutlined:<AccountBookOutlined />,
        PieChartFilled:<PieChartFilled />,
        IdcardFilled:<IdcardFilled />,
        PlayCircleOutlined:<PlayCircleOutlined />,
        CheckCircleOutlined:<CheckCircleOutlined />,
        CloseCircleOutlined:<CloseCircleOutlined />,
        ExclamationCircleOutlined:<ExclamationCircleOutlined />,
        CheckSquareOutlined: <CheckSquareOutlined />,
        FileSearchOutlined:<FileSearchOutlined />,
        SmallDashOutlined:<SmallDashOutlined />,
        RiseOutlined:<RiseOutlined />,
        RetweetOutlined:<RetweetOutlined />,
        SettingOutlined:<SettingOutlined />,
        QuestionCircleOutlined:<QuestionCircleOutlined />,

}
export {icon};
export default icon;
