<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'description' => null],
            ['name' => 'Albania', 'code' => 'AL', 'description' => null],
            ['name' => 'Algeria', 'code' => 'DZ', 'description' => null],
            ['name' => 'Andorra', 'code' => 'AD', 'description' => null],
            ['name' => 'Angola', 'code' => 'AO', 'description' => null],
            ['name' => 'Argentina', 'code' => 'AR', 'description' => null],
            ['name' => 'Armenia', 'code' => 'AM', 'description' => null],
            ['name' => 'Australia', 'code' => 'AU', 'description' => null],
            ['name' => 'Austria', 'code' => 'AT', 'description' => null],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'description' => null],
            ['name' => 'Bahamas', 'code' => 'BS', 'description' => null],
            ['name' => 'Bahrain', 'code' => 'BH', 'description' => null],
            ['name' => 'Bangladesh', 'code' => 'BD', 'description' => null],
            ['name' => 'Belarus', 'code' => 'BY', 'description' => null],
            ['name' => 'Belgium', 'code' => 'BE', 'description' => null],
            ['name' => 'Belize', 'code' => 'BZ', 'description' => null],
            ['name' => 'Benin', 'code' => 'BJ', 'description' => null],
            ['name' => 'Bhutan', 'code' => 'BT', 'description' => null],
            ['name' => 'Bolivia', 'code' => 'BO', 'description' => null],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'description' => null],
            ['name' => 'Botswana', 'code' => 'BW', 'description' => null],
            ['name' => 'Brazil', 'code' => 'BR', 'description' => null],
            ['name' => 'Brunei', 'code' => 'BN', 'description' => null],
            ['name' => 'Bulgaria', 'code' => 'BG', 'description' => null],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'description' => null],
            ['name' => 'Burundi', 'code' => 'BI', 'description' => null],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'description' => null],
            ['name' => 'Cambodia', 'code' => 'KH', 'description' => null],
            ['name' => 'Cameroon', 'code' => 'CM', 'description' => null],
            ['name' => 'Canada', 'code' => 'CA', 'description' => null],
            ['name' => 'Central African Republic', 'code' => 'CF', 'description' => null],
            ['name' => 'Chad', 'code' => 'TD', 'description' => null],
            ['name' => 'Chile', 'code' => 'CL', 'description' => null],
            ['name' => 'China', 'code' => 'CN', 'description' => null],
            ['name' => 'Colombia', 'code' => 'CO', 'description' => null],
            ['name' => 'Comoros', 'code' => 'KM', 'description' => null],
            ['name' => 'Congo (Congo-Brazzaville)', 'code' => 'CG', 'description' => null],
            ['name' => 'Costa Rica', 'code' => 'CR', 'description' => null],
            ['name' => 'Croatia', 'code' => 'HR', 'description' => null],
            ['name' => 'Cuba', 'code' => 'CU', 'description' => null],
            ['name' => 'Cyprus', 'code' => 'CY', 'description' => null],
            ['name' => 'Czechia (Czech Republic)', 'code' => 'CZ', 'description' => null],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'CD', 'description' => null],
            ['name' => 'Denmark', 'code' => 'DK', 'description' => null],
            ['name' => 'Djibouti', 'code' => 'DJ', 'description' => null],
            ['name' => 'Dominica', 'code' => 'DM', 'description' => null],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'description' => null],
            ['name' => 'Ecuador', 'code' => 'EC', 'description' => null],
            ['name' => 'Egypt', 'code' => 'EG', 'description' => null],
            ['name' => 'El Salvador', 'code' => 'SV', 'description' => null],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'description' => null],
            ['name' => 'Eritrea', 'code' => 'ER', 'description' => null],
            ['name' => 'Estonia', 'code' => 'EE', 'description' => null],
            ['name' => 'Eswatini (fmr. "Swaziland")', 'code' => 'SZ', 'description' => null],
            ['name' => 'Ethiopia', 'code' => 'ET', 'description' => null],
            ['name' => 'Fiji', 'code' => 'FJ', 'description' => null],
            ['name' => 'Finland', 'code' => 'FI', 'description' => null],
            ['name' => 'France', 'code' => 'FR', 'description' => null],
            ['name' => 'Gabon', 'code' => 'GA', 'description' => null],
            ['name' => 'Gambia', 'code' => 'GM', 'description' => null],
            ['name' => 'Georgia', 'code' => 'GE', 'description' => null],
            ['name' => 'Germany', 'code' => 'DE', 'description' => null],
            ['name' => 'Ghana', 'code' => 'GH', 'description' => null],
            ['name' => 'Greece', 'code' => 'GR', 'description' => null],
            ['name' => 'Grenada', 'code' => 'GD', 'description' => null],
            ['name' => 'Guatemala', 'code' => 'GT', 'description' => null],
            ['name' => 'Guinea', 'code' => 'GN', 'description' => null],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'description' => null],
            ['name' => 'Guyana', 'code' => 'GY', 'description' => null],
            ['name' => 'Haiti', 'code' => 'HT', 'description' => null],
            ['name' => 'Holy See', 'code' => 'VA', 'description' => null],
            ['name' => 'Honduras', 'code' => 'HN', 'description' => null],
            ['name' => 'Hungary', 'code' => 'HU', 'description' => null],
            ['name' => 'Iceland', 'code' => 'IS', 'description' => null],
            ['name' => 'India', 'code' => 'IN', 'description' => null],
            ['name' => 'Indonesia', 'code' => 'ID', 'description' => null],
            ['name' => 'Iran', 'code' => 'IR', 'description' => null],
            ['name' => 'Iraq', 'code' => 'IQ', 'description' => null],
            ['name' => 'Ireland', 'code' => 'IE', 'description' => null],
            ['name' => 'Israel', 'code' => 'IL', 'description' => null],
            ['name' => 'Italy', 'code' => 'IT', 'description' => null],
            ['name' => 'Jamaica', 'code' => 'JM', 'description' => null],
            ['name' => 'Japan', 'code' => 'JP', 'description' => null],
            ['name' => 'Jordan', 'code' => 'JO', 'description' => null],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'description' => null],
            ['name' => 'Kenya', 'code' => 'KE', 'description' => null],
            ['name' => 'Kiribati', 'code' => 'KI', 'description' => null],
            ['name' => 'Kuwait', 'code' => 'KW', 'description' => null],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'description' => null],
            ['name' => 'Laos', 'code' => 'LA', 'description' => null],
            ['name' => 'Latvia', 'code' => 'LV', 'description' => null],
            ['name' => 'Lebanon', 'code' => 'LB', 'description' => null],
            ['name' => 'Lesotho', 'code' => 'LS', 'description' => null],
            ['name' => 'Liberia', 'code' => 'LR', 'description' => null],
            ['name' => 'Libya', 'code' => 'LY', 'description' => null],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'description' => null],
            ['name' => 'Lithuania', 'code' => 'LT', 'description' => null],
            ['name' => 'Luxembourg', 'code' => 'LU', 'description' => null],
            ['name' => 'Madagascar', 'code' => 'MG', 'description' => null],
            ['name' => 'Malawi', 'code' => 'MW', 'description' => null],
            ['name' => 'Malaysia', 'code' => 'MY', 'description' => null],
            ['name' => 'Maldives', 'code' => 'MV', 'description' => null],
            ['name' => 'Mali', 'code' => 'ML', 'description' => null],
            ['name' => 'Malta', 'code' => 'MT', 'description' => null],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'description' => null],
            ['name' => 'Mauritania', 'code' => 'MR', 'description' => null],
            ['name' => 'Mauritius', 'code' => 'MU', 'description' => null],
            ['name' => 'Mexico', 'code' => 'MX', 'description' => null],
            ['name' => 'Micronesia', 'code' => 'FM', 'description' => null],
            ['name' => 'Moldova', 'code' => 'MD', 'description' => null],
            ['name' => 'Monaco', 'code' => 'MC', 'description' => null],
            ['name' => 'Mongolia', 'code' => 'MN', 'description' => null],
            ['name' => 'Montenegro', 'code' => 'ME', 'description' => null],
            ['name' => 'Morocco', 'code' => 'MA', 'description' => null],
            ['name' => 'Mozambique', 'code' => 'MZ', 'description' => null],
            ['name' => 'Myanmar (formerly Burma)', 'code' => 'MM', 'description' => null],
            ['name' => 'Namibia', 'code' => 'NA', 'description' => null],
            ['name' => 'Nauru', 'code' => 'NR', 'description' => null],
            ['name' => 'Nepal', 'code' => 'NP', 'description' => null],
            ['name' => 'Netherlands', 'code' => 'NL', 'description' => null],
            ['name' => 'New Zealand', 'code' => 'NZ', 'description' => null],
            ['name' => 'Nicaragua', 'code' => 'NI', 'description' => null],
            ['name' => 'Niger', 'code' => 'NE', 'description' => null],
            ['name' => 'Nigeria', 'code' => 'NG', 'description' => null],
            ['name' => 'North Korea', 'code' => 'KP', 'description' => null],
            ['name' => 'North Macedonia', 'code' => 'MK', 'description' => null],
            ['name' => 'Norway', 'code' => 'NO', 'description' => null],
            ['name' => 'Oman', 'code' => 'OM', 'description' => null],
            ['name' => 'Pakistan', 'code' => 'PK', 'description' => null],
            ['name' => 'Palau', 'code' => 'PW', 'description' => null],
            ['name' => 'Palestine State', 'code' => 'PS', 'description' => null],
            ['name' => 'Panama', 'code' => 'PA', 'description' => null],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'description' => null],
            ['name' => 'Paraguay', 'code' => 'PY', 'description' => null],
            ['name' => 'Peru', 'code' => 'PE', 'description' => null],
            ['name' => 'Philippines', 'code' => 'PH', 'description' => null],
            ['name' => 'Poland', 'code' => 'PL', 'description' => null],
            ['name' => 'Portugal', 'code' => 'PT', 'description' => null],
            ['name' => 'Qatar', 'code' => 'QA', 'description' => null],
            ['name' => 'Romania', 'code' => 'RO', 'description' => null],
            ['name' => 'Russia', 'code' => 'RU', 'description' => null],
            ['name' => 'Rwanda', 'code' => 'RW', 'description' => null],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'description' => null],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'description' => null],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'description' => null],
            ['name' => 'Samoa', 'code' => 'WS', 'description' => null],
            ['name' => 'San Marino', 'code' => 'SM', 'description' => null],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'description' => null],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'description' => null],
            ['name' => 'Senegal', 'code' => 'SN', 'description' => null],
            ['name' => 'Serbia', 'code' => 'RS', 'description' => null],
            ['name' => 'Seychelles', 'code' => 'SC', 'description' => null],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'description' => null],
            ['name' => 'Singapore', 'code' => 'SG', 'description' => null],
            ['name' => 'Slovakia', 'code' => 'SK', 'description' => null],
            ['name' => 'Slovenia', 'code' => 'SI', 'description' => null],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'description' => null],
            ['name' => 'Somalia', 'code' => 'SO', 'description' => null],
            ['name' => 'South Africa', 'code' => 'ZA', 'description' => null],
            ['name' => 'South Korea', 'code' => 'KR', 'description' => null],
            ['name' => 'South Sudan', 'code' => 'SS', 'description' => null],
            ['name' => 'Spain', 'code' => 'ES', 'description' => null],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'description' => null],
            ['name' => 'Sudan', 'code' => 'SD', 'description' => null],
            ['name' => 'Suriname', 'code' => 'SR', 'description' => null],
            ['name' => 'Sweden', 'code' => 'SE', 'description' => null],
            ['name' => 'Switzerland', 'code' => 'CH', 'description' => null],
            ['name' => 'Syria', 'code' => 'SY', 'description' => null],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'description' => null],
            ['name' => 'Tanzania', 'code' => 'TZ', 'description' => null],
            ['name' => 'Thailand', 'code' => 'TH', 'description' => null],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'description' => null],
            ['name' => 'Togo', 'code' => 'TG', 'description' => null],
            ['name' => 'Tonga', 'code' => 'TO', 'description' => null],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'description' => null],
            ['name' => 'Tunisia', 'code' => 'TN', 'description' => null],
            ['name' => 'Turkey', 'code' => 'TR', 'description' => null],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'description' => null],
            ['name' => 'Tuvalu', 'code' => 'TV', 'description' => null],
            ['name' => 'Uganda', 'code' => 'UG', 'description' => null],
            ['name' => 'Ukraine', 'code' => 'UA', 'description' => null],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'description' => null],
            ['name' => 'United Kingdom', 'code' => 'GB', 'description' => null],
            ['name' => 'United States of America', 'code' => 'US', 'description' => null],
            ['name' => 'Uruguay', 'code' => 'UY', 'description' => null],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'description' => null],
            ['name' => 'Vanuatu', 'code' => 'VU', 'description' => null],
            ['name' => 'Venezuela', 'code' => 'VE', 'description' => null],
            ['name' => 'Vietnam', 'code' => 'VN', 'description' => null],
            ['name' => 'Yemen', 'code' => 'YE', 'description' => null],
            ['name' => 'Zambia', 'code' => 'ZM', 'description' => null],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'description' => null],
        ];

        DB::table('countries')->insert($countries);
    }
};